[build]
publish = "."

[[redirects]]
from = "https://www.jaechung.org/*"
to = "https://jaechung.org/:splat"
status = 301
force = true

[[headers]]
for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
